### ISSUE TITLE
Consider still calling getCorrectFileName()

### ISSUE THREAD

**Issue by dbraito-bsd** [obsergiu/magento-wysiwyg-thumbail-fix#1]
What a crazy bug. I just installed a vanilla 1.9.4.1, and sure enough, this bug causes all thumbnails to be regenerated everytime you view them in 'Media Storage'. This will take down people's ability to use this screen.

Anyway, in your fix I see you are not calling getCorrectFileName(). I propose that a better fix would be to do this:

    $thumbPath = pathinfo($item->getFilename(), PATHINFO_DIRNAME);
    $thumbUrl = $this->getThumbnailUrl($thumbPath . DS .  Mage_Core_Model_File_Uploader::getCorrectFileName($item->getBasename()), true);

Then you are still running Magento's filename checker. I guess this code would protect the site in the event that someone altered filenames in the database, or tried to name a file on disk some kind of javascript code.

Anyway thanks for posting this repo and validating the issue.

**Comment by obsergiu** [comment]
That's a good suggestion.

I've added it into the file.
Thanks @dbraito-bsd
